name: E2E Tests and Lighthouse Audit

on:
  workflow_run:
    workflows: ['Deploy to Cloudflare Workers']
    types:
      - completed

jobs:
  e2e-tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test --reporter=html

      - name: Copy Playwright HTML Report to Root
        run: |
          mkdir -p playwright-report/html-report
          cp -r playwright-report/index.html/* playwright-report/html-report/
          cp -r playwright-report/html-report/* playwright-report/

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

  lighthouse:
    name: Lighthouse Audit + Viewer
    needs: e2e-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Download Playwright Report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Run Lighthouse CI and Export HTML Reports
        run: |
          mkdir -p playwright-report/lighthouse

          lhci collect \
            --url=https://jaman7-wongapl-rekrutacja-web-254455.pages.dev \
            --url=https://jaman7-wongapl-rekrutacja-web-254455.pages.dev/blog \
            --url=https://jaman7-wongapl-rekrutacja-web-254455.pages.dev/blog/page/1 \
            --numberOfRuns=3 \
            --config=./.lighthouserc.js || echo "Lighthouse failed, continuing..."

          # Kopiowanie raportów Lighthouse
          cp .lighthouseci/*.html playwright-report/lighthouse/

          # Tworzenie index.html w folderze lighthouse
          echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Lighthouse Reports</title></head><body><h1>Lighthouse Reports</h1><ul>" > playwright-report/lighthouse/index.html
          for file in playwright-report/lighthouse/*.html; do
            fname=$(basename "$file")
            echo "<li><a href='$fname'>$fname</a></li>" >> playwright-report/lighthouse/index.html
          done
          echo "<li><a href='../report.html'>Playwright Report</a></li>" >> playwright-report/lighthouse/index.html
          echo "</ul></body></html>" >> playwright-report/lighthouse/index.html

          # Główna strona - linki do raportów
          echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>E2E Reports</title></head><body><h1>E2E Reports</h1><ul>" > playwright-report/index.html
          echo "<li><a href='report.html'>Playwright Report</a></li>" >> playwright-report/index.html
          echo "<li><a href='lighthouse/index.html'>Lighthouse Report</a></li>" >> playwright-report/index.html
          echo "</ul></body></html>" >> playwright-report/index.html

      - name: Upload Combined Report
        uses: actions/upload-artifact@v4
        with:
          name: full-report
          path: playwright-report

  deploy-report:
    name: Deploy Reports to Cloudflare Pages
    needs: lighthouse
    runs-on: ubuntu-latest

    steps:
      - name: Download final report artifact
        uses: actions/download-artifact@v4
        with:
          name: full-report
          path: playwright-report

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_E2E_PROJECT }}
          directory: playwright-report
          branch: main
